name: Algorithms CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-latest, ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
#     - name: configure
#       run: ./configure
    - name: build project
      run: mkdir build && cd build && cmake .. && make
    - name: run tests
      run: find . -print | sed -e "s;[^/]*/;|____;g;s;____|; |;g"
    - name: print repo
      run: find . -print | sed -e "s;[^/]*/;|____;g;s;____|; |;g"
