name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: setup_folder
      run: mkdir build
    - name: setup_path
      run: cd build
    - name: build cmake
      run: cmake ..
    - name: start make
      run: make
