name: Algorithms CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-latest, ubuntu-16.04] # previous builds: windows-2019, windows-latest
    

    steps:
    - uses: actions/checkout@v2
#     - name: configure
#       run: ./configure
    - name: configure
      run: mkdir build && cd build && cmake .. && make
#     - name: build cmake
#       run: cmake ..
#     - name: start make
#       run: make
