name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue hasn't been activate, so I'm marking this as stale. If this was incorrect, please comment 'This issue is not stale.'"
        stale-pr-message: "This PR hasn't been activate, so I'm marking this as stale. If this was incorrect, please comment 'This PR is not stale.'"
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pr'
